version: "3"
services:
    fdb-coordinator:
        image: foundationdb/foundationdb:${FDB_VERSION}
        environment:
            FDB_COORDINATOR: ${FDB_COORDINATOR}
            FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
            FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}
    fdb-server-1:
        depends_on:
            - fdb-coordinator
        image: foundationdb/foundationdb:${FDB_VERSION}
        environment:
            FDB_COORDINATOR: ${FDB_COORDINATOR}
            FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
            FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}
    fdb-server-2:
        depends_on:
            - fdb-coordinator
        image: foundationdb/foundationdb:${FDB_VERSION}
        environment:
            FDB_COORDINATOR: ${FDB_COORDINATOR}
            FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
            FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}
